{"name": "test_authorization_no_valid", "status": "passed", "description": "authorization no valid", "steps": [{"name": "authorization no valid", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Неверные данные для авторизации\nMessage: unexpected alert open: {Alert text : Неверные данные для авторизации}\n  (Session info: chrome=120.0.6099.217)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6DC7E4D02+56194]\n\t(No symbol) [0x00007FF6DC7504B2]\n\t(No symbol) [0x00007FF6DC5F76AA]\n\t(No symbol) [0x00007FF6DC682B5C]\n\t(No symbol) [0x00007FF6DC665C23]\n\t(No symbol) [0x00007FF6DC634A45]\n\t(No symbol) [0x00007FF6DC635AD4]\n\tGetHandleVerifier [0x00007FF6DCB5D5BB+3695675]\n\tGetHandleVerifier [0x00007FF6DCBB6197+4059159]\n\tGetHandleVerifier [0x00007FF6DCBADF63+4025827]\n\tGetHandleVerifier [0x00007FF6DC87F029+687785]\n\t(No symbol) [0x00007FF6DC75B508]\n\t(No symbol) [0x00007FF6DC757564]\n\t(No symbol) [0x00007FF6DC7576E9]\n\t(No symbol) [0x00007FF6DC748094]\n\tBaseThreadInitThunk [0x00007FFF70C77344+20]\n\tRtlUserThreadStart [0x00007FFF71B826B1+33]\n\n", "trace": "  File \"C:\\Users\\User\\Desktop\\phyton\\pythonProject\\autorizationMirapolis\\pages\\authorization.py\", line 141, in authorization_no_valid\n    Logger.add_end_step(url=self.driver.current_url, method='authorization_no_valid')\n                            ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in current_url\n    return self.execute(Command.GET_CURRENT_URL)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1708283354642, "stop": 1708283361960}], "attachments": [{"name": "stdout", "source": "c47cc64e-ddd3-4536-9a26-2969a6054f6e-attachment.txt", "type": "text/plain"}], "start": 1708283354642, "stop": 1708283364977, "uuid": "5541c6d8-f536-4f7b-816c-88db0fe583b2", "historyId": "a98472491dee5654d4caa97b26fdb0aa", "testCaseId": "a98472491dee5654d4caa97b26fdb0aa", "fullName": "tests.test_autohrization#test_authorization_no_valid", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_autohrization"}, {"name": "host", "value": "DESKTOP-6HL54QF"}, {"name": "thread", "value": "9896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_autohrization"}]}